### ISSUE TITLE
The FakeAVCeleb Seems Not Available Now

### ISSUE THREAD

**Issue by JoeLeelyf** [JoeLeelyf/OpenAVFF#1]
We tried a several times to apply the FakeAVCeleb, which the original AVFF mainly performs its experiments on, but failed to recieve any reply. We would really appreciate it if you could provide us with ways of getting the dataset :)

**Comment by JoeLeelyf** [comment]
After waiting a long time, we received the download link of FakeAVCeleb.

**Comment by tuffy-studio** [comment]
Hello, I’m also applying for this dataset and have encountered the same issue as you. Despite filling out the form a several times, I still haven’t received the download link. Could you kindly share the dataset? Thank you so much!

**Comment by JoeLeelyf** [comment]
The download link they provide via Google Drive has expired, and all my local copies have also been deleted. Sorry for my failing to offer any help.

**Comment by tuffy-studio** [comment]
感谢回复！没关系的，我再多申请几次吧。助您在2025年科研顺利，成果多多！
