### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by 123308** [JoeLeelyf/OpenAVFF#3]
作者能上传kaggle数据集链接吗，原kaggle网站中下载链接失效了，如果可以万分感谢

**Comment by JoeLeelyf** [comment]
一阶段还是二阶段的数据？

**Comment by 123308** [comment]
两个阶段的都失效了，麻烦大佬上传一下

**Comment by JoeLeelyf** [comment]
我刚刚看了一下比赛之后我这边的数据集都删完了，十分抱歉😞
